version: '3'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./deploy/docker/Dockerfile.dev
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    ports: 
      - 8080:8080 
      - 4000:4000 
      - 6060:6060 
    restart: on-failure
    networks:
      - fullstack
    volumes:
      - ${HOME}/.config/gh:/home/vscode/.config/gh
      - ${HOME}/.ssh:/home/vscode/.ssh
  
# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge

