version: '3'
services:
  myapp:
    container_name: myapp
    build:
      context: .
      dockerfile: ./deploy/docker/Dockerfile.dev
      args:
        - USER_ID=1000
        - GROUP_ID=1000
    ports: 
      - 3000:3000
    restart: on-failure
    networks:
      - myapp-network
    volumes:
      - ${HOME}/.config/gh:/home/vscode/.config/gh
      - ${HOME}/.ssh:/home/vscode/.ssh
  
# Networks to be created to facilitate communication between containers
networks:
  myapp-network:
    driver: bridge

